const weeks=[
{week:1,title:"1:00 run / 4:00 walk",meta:"6 rounds • 30 min total • 6 min running",seq:Array.from({length:6},(_,i)=>[["RUN",60],...(i<5?[["WALK",240]]:[])]).flat()},
{week:2,title:"2:00 run / 3:00 walk",meta:"6 rounds • 30 min total • 12 min running",seq:Array.from({length:6},(_,i)=>[["RUN",120],...(i<5?[["WALK",180]]:[])]).flat()},
{week:3,title:"3:00 run / 2:00 walk",meta:"6 rounds • 30 min total • 18 min running",seq:Array.from({length:6},(_,i)=>[["RUN",180],...(i<5?[["WALK",120]]:[])]).flat()},
{week:4,title:"4:00 run / 1:00 walk",meta:"6 rounds • 30 min total • 24 min running",seq:Array.from({length:6},(_,i)=>[["RUN",240],...(i<5?[["WALK",60]]:[])]).flat()},
{week:5,title:"6:00 run / 2:00 walk",meta:"3 rounds • 24 min running",seq:[["RUN",360],["WALK",120],["RUN",360],["WALK",120],["RUN",360]]},
{week:6,title:"9:00 run / 1:00 walk",meta:"3 rounds • 27 min running",seq:[["RUN",540],["WALK",60],["RUN",540],["WALK",60],["RUN",540]]},
{week:7,title:"14:00 run / 1:00 walk",meta:"2 rounds • 28 min running",seq:[["RUN",840],["WALK",60],["RUN",840]]},
{week:8,title:"30:00 continuous easy run",meta:"Goal week • no walking",seq:[["RUN",1800]]}
];
const lifts={A:{title:"A — Horizontal",exercises:[["Upper horizontal push","Bench Press","3 × 6–10"],["Lower pull","Romanian Deadlift","3 × 6–10"],["Upper horizontal pull","Chest-Supported Row","3 × 6–10"],["Lower push","Leg Press or Squat","3 × 6–10"],["Arm superset","DB Curl + Triceps Pressdown","2 × 8–12 each"]]},B:{title:"B — Vertical",exercises:[["Upper vertical push","DB Shoulder Press","3 × 6–10"],["Lower pull","Hip Thrust","3 × 8–10"],["Upper vertical pull","Lat Pulldown / Assisted Pull-up","3 × 6–10"],["Lower push","Bulgarian Split Squat","3 × 6–10 / leg"],["Arm superset","Hammer Curl + Overhead Triceps Extension","2 × 8–12 each"]]}};
const finishers=[{name:"Classic",moves:["Mountain Climbers","Push-ups","Bodyweight Squats","Burpees","Plank"]},{name:"Legs + Core",moves:["Bodyweight Squats","Reverse Lunges","Plank Shoulder Taps","Jumping Lunges","Dead Bug"]},{name:"Upper + Core",moves:["Push-ups","Mountain Climbers","Squat Thrusts","Push-up → Shoulder Tap","Plank Knee Drives"]},{name:"Athletic",moves:["Skater Hops","Push-ups","Jumping Lunges","Mountain Climbers","Burpees"]}];
let currentWeek=Number(localStorage.getItem("currentWeek")||2),liftType=localStorage.getItem("liftType")||"A";
let timer={seq:[],idx:0,remaining:0,running:false,interval:null,kind:"",title:""};
const $=id=>document.getElementById(id);
function renderWeeks(){const w=weeks.find(x=>x.week===currentWeek);$("statusPill").textContent=`Week ${currentWeek}`;$("currentWeekTitle").textContent=`Week ${currentWeek}`;$("currentWeekPlan").textContent=w.title;$("currentWeekMeta").textContent=w.meta;$("weekCards").innerHTML=weeks.map(x=>`<button class="card week-card ${x.week===currentWeek?"current":""}" data-week="${x.week}"><div class="week-label">WEEK ${x.week}</div><div><div class="card-title">${x.title}</div><div class="card-sub">${x.meta}</div></div><div class="check">${x.week===currentWeek?"✓":""}</div></button>`).join("");document.querySelectorAll("[data-week]").forEach(b=>b.addEventListener("click",()=>{currentWeek=Number(b.dataset.week);localStorage.setItem("currentWeek",currentWeek);renderWeeks()}))}
function getLogs(){return JSON.parse(localStorage.getItem(`liftLogs-${liftType}`)||"{}")}function saveLog(i,v){const logs=getLogs();logs[i]=v;localStorage.setItem(`liftLogs-${liftType}`,JSON.stringify(logs))}
function renderLift(){const p=lifts[liftType],logs=getLogs();$("liftTitle").textContent=p.title;$("liftABtn").classList.toggle("active",liftType==="A");$("liftBBtn").classList.toggle("active",liftType==="B");$("exerciseCards").innerHTML=p.exercises.map((e,i)=>`<div class="card exercise-card"><div><div class="move-label">${e[0]}</div><div class="card-title">${e[1]}</div><div class="card-sub">${e[2]}</div></div><div class="log-wrap"><input class="log-input" data-log="${i}" placeholder="e.g. 185: 8,8,7"><div class="last">${logs[i]?`Last: ${logs[i]}`:"No previous entry"}</div></div></div>`).join("");document.querySelectorAll("[data-log]").forEach(inp=>inp.addEventListener("change",()=>{saveLog(inp.dataset.log,inp.value.trim());renderLift()}))}
function renderFinishers(){$("finisherCards").innerHTML=finishers.map((f,i)=>`<div class="card finisher-card"><div class="finisher-row"><div><div class="card-title">${f.name}</div><div class="card-sub">2:30 × 3 rounds • 1:00 rest between</div></div><button class="secondary" data-fin="${i}">Start</button></div><ol class="finisher-list">${f.moves.map(m=>`<li>${m} — 0:30</li>`).join("")}</ol></div>`).join("");document.querySelectorAll("[data-fin]").forEach(b=>b.addEventListener("click",()=>startFinisher(Number(b.dataset.fin))))}
function switchView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===id));window.scrollTo(0,0)}
const totalTime=seq=>seq.reduce((a,x)=>a+x[1],0);const formatTime=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,"0")}:${String(Math.max(0,s)%60).padStart(2,"0")}`;
function signal(){if(navigator.vibrate)navigator.vibrate(120);try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),osc=ctx.createOscillator(),gain=ctx.createGain();gain.gain.value=.05;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.12)}catch(e){}}
function loadTimer(seq,kind,title){clearInterval(timer.interval);timer={seq:[...seq],idx:0,remaining:seq[0]?.[1]||0,running:false,interval:null,kind,title};$("timerKind").textContent=kind.toUpperCase();$("timerTitle").textContent=seq[0]?.[0]||"Ready";$("timerClock").textContent=formatTime(totalTime(seq));$("timerSub").textContent=title;$("timerStartPauseBtn").textContent="Start";renderQueue();switchView("timerView")}
function startRun(){const w=weeks.find(x=>x.week===currentWeek);loadTimer(w.seq,"Run Timer",`Week ${w.week} • ${w.title}`)}
function startFinisher(i){const f=finishers[i],seq=[];for(let r=1;r<=3;r++){f.moves.forEach(m=>seq.push([`${m} • R${r}`,30]));if(r<3)seq.push([`REST • after R${r}`,60])}loadTimer(seq,"Finisher",`${f.name} • 9:30 total`)}
function renderQueue(){$("timerQueue").innerHTML=timer.seq.map((x,i)=>`<div class="queue-item ${i===timer.idx?"active":""}">${i+1}. ${x[0]} — ${formatTime(x[1])}</div>`).join("")}
function tick(){timer.remaining--;if(timer.remaining<=0){signal();timer.idx++;if(timer.idx>=timer.seq.length){clearInterval(timer.interval);timer.running=false;timer.remaining=0;$("timerTitle").textContent="DONE ✓";$("timerClock").textContent="00:00";$("timerSub").textContent="Workout complete";$("timerStartPauseBtn").textContent="Start";renderQueue();return}timer.remaining=timer.seq[timer.idx][1];renderQueue()}$("timerTitle").textContent=timer.seq[timer.idx]?.[0]||"Ready";$("timerClock").textContent=formatTime(timer.remaining)}
function toggleTimer(){if(!timer.seq.length)return;if(!timer.running){timer.running=true;$("timerStartPauseBtn").textContent="Pause";$("timerClock").textContent=formatTime(timer.remaining);timer.interval=setInterval(tick,1000)}else{timer.running=false;clearInterval(timer.interval);$("timerStartPauseBtn").textContent="Resume"}}
function resetTimer(){clearInterval(timer.interval);if(!timer.seq.length)return;timer.idx=0;timer.remaining=timer.seq[0][1];timer.running=false;$("timerTitle").textContent=timer.seq[0][0];$("timerClock").textContent=formatTime(totalTime(timer.seq));$("timerStartPauseBtn").textContent="Start";renderQueue()}
$("startRunBtn").addEventListener("click",startRun);$("liftABtn").addEventListener("click",()=>{liftType="A";localStorage.setItem("liftType",liftType);renderLift()});$("liftBBtn").addEventListener("click",()=>{liftType="B";localStorage.setItem("liftType",liftType);renderLift()});$("timerStartPauseBtn").addEventListener("click",toggleTimer);$("timerResetBtn").addEventListener("click",resetTimer);document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));renderWeeks();renderLift();renderFinishers();if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))}
